In [2]:
import pandas as pd
df=pd.read_csv(r"Esophageal_Dataset.csv")
df

,Unnamed: 0,patient_barcode,tissue_source_site,patient_id,bcr_patient_uuid,informed_consent_verified,icd_o_3_site,icd_o_3_histology,icd_10,tissue_prospective_collection_indicator,...,primary_pathology_lymph_node_examined_count,primary_pathology_number_of_lymphnodes_positive_by_he,primary_pathology_number_of_lymphnodes_positive_by_ihc,primary_pathology_planned_surgery_status,primary_pathology_treatment_prior_to_surgery,primary_pathology_residual_tumor,primary_pathology_karnofsky_performance_score,primary_pathology_eastern_cancer_oncology_group,primary_pathology_radiation_therapy,primary_pathology_postoperative_rx_tx
0,0,TCGA-2H-A9GF,2H,A9GF,0500F1A6-A528-43F3-B035-12D3B7C99C0F,YES,C15.5,8140/3,C15.5,NO,...,8.0,7.0,0.0,NaN,NaN,R1,NaN,NaN,NO,NO
1,1,TCGA-2H-A9GG,2H,A9GG,70084008-697D-442D-8F74-C12F8F598570,YES,C15.5,8140/3,C15.5,NO,...,19.0,4.0,0.0,NaN,NaN,R1,NaN,NaN,NO,NO
2,2,TCGA-2H-A9GH,2H,A9GH,606DC5B8-7625-42A6-A936-504EF25623A4,YES,C15.5,8140/3,C15.5,NO,...,30.0,1.0,0.0,NaN,NaN,R0,NaN,NaN,NO,NO
3,3,TCGA-2H-A9GI,2H,A9GI,CEAF98F8-517E-457A-BF29-ACFE22893D49,YES,C15.5,8140/3,C15.5,NO,...,8.0,4.0,0.0,NaN,NaN,R0,NaN,NaN,NO,NO
4,4,TCGA-2H-A9GJ,2H,A9GJ,EE47CD59-C8D8-4B1E-96DB-91C679E4106F,YES,C15.5,8140/3,C15.5,NO,...,19.0,0.0,0.0,NaN,NaN,R0,NaN,NaN,NO,NO
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3980,3995,677b83fe-4dbd-410e-aea8-62d68a80f652,Z6,A8JD,B997D486-8C71-4926-9DF1-D2AFDAF2785F,YES,C15.9,8070/3,C15.9,YES,...,19.0,0.0,0.0,NaN,NaN,R0,90.0,2.0,NaN,NaN
3981,3996,a4faa9ff-b9a1-4a4c-9929-bb0154030067,Z6,A8JE,1116DDAE-76B0-48D6-869C-BE65D8B09D35,YES,C15.3,8070/3,C15.3,YES,...,9.0,1.0,0.0,Surgery already performed,No Treatment,RX,80.0,2.0,NaN,NaN
3982,3997,6bdc4fc8-8d76-4886-bf13-e282f4b1476b,Z6,A9VB,1C2837D4-BD2C-46F7-9E22-683B82A16350,YES,C15.5,8070/3,C15.5,YES,...,NaN,NaN,NaN,NaN,NaN,R0,NaN,NaN,NO,NO
3983,3998,d61e44e1-06ed-4849-85d7-3b360dd03721,Z6,AAPN,2659BB79-95F9-4476-A516-F3800536422D,YES,C15.5,8070/3,C15.5,YES,...,11.0,0.0,NaN,NaN,NaN,R0,NaN,NaN,NO,NO
3984,3999,20459cd1-73f5-4b54-8f86-406247c575f7,ZR,A9CJ,FDCDF592-66F1-4027-962F-A64D49BE474F,YES,C15.5,8140/3,C15.5,NO,...,24.0,12.0,0.0,NaN,NaN,R0,NaN,NaN,NO,NO

In [3]:
print(df.columns)

Index(['Unnamed: 0', 'patient_barcode', 'tissue_source_site', 'patient_id',
       'bcr_patient_uuid', 'informed_consent_verified', 'icd_o_3_site',
       'icd_o_3_histology', 'icd_10',
       'tissue_prospective_collection_indicator',
       'tissue_retrospective_collection_indicator', 'days_to_birth',
       'country_of_birth', 'gender', 'height', 'weight',
       'country_of_procurement', 'state_province_of_procurement',
       'city_of_procurement', 'race_list', 'ethnicity', 'other_dx',
       'history_of_neoadjuvant_treatment', 'person_neoplasm_cancer_status',
       'vital_status', 'days_to_last_followup', 'days_to_death',
       'tobacco_smoking_history', 'age_began_smoking_in_years',
       'stopped_smoking_year', 'number_pack_years_smoked',
       'alcohol_history_documented', 'frequency_of_alcohol_consumption',
       'amount_of_alcohol_consumption_per_day', 'reflux_history',
       'antireflux_treatment_types', 'h_pylori_infection',
       'initial_diagnosis_by', 'barretts_esophagus', 'goblet_cells_present',
       'history_of_esophageal_cancer', 'number_of_relatives_diagnosed',
       'has_new_tumor_events_information', 'day_of_form_completion',
       'month_of_form_completion', 'year_of_form_completion',
       'has_follow_ups_information', 'has_drugs_information',
       'has_radiations_information', 'project', 'stage_event_system_version',
       'stage_event_clinical_stage', 'stage_event_pathologic_stage',
       'stage_event_tnm_categories', 'stage_event_psa',
       'stage_event_gleason_grading', 'stage_event_ann_arbor',
       'stage_event_serum_markers', 'stage_event_igcccg_stage',
       'stage_event_masaoka_stage', 'primary_pathology_tumor_tissue_site',
       'primary_pathology_esophageal_tumor_cental_location',
       'primary_pathology_esophageal_tumor_involvement_sites',
       'primary_pathology_histological_type',
       'primary_pathology_columnar_metaplasia_present',
       'primary_pathology_columnar_mucosa_goblet_cell_present',
       'primary_pathology_columnar_mucosa_dysplasia',
       'primary_pathology_neoplasm_histologic_grade',
       'primary_pathology_days_to_initial_pathologic_diagnosis',
       'primary_pathology_age_at_initial_pathologic_diagnosis',
       'primary_pathology_year_of_initial_pathologic_diagnosis',
       'primary_pathology_initial_pathologic_diagnosis_method',
       'primary_pathology_init_pathology_dx_method_other',
       'primary_pathology_lymph_node_metastasis_radiographic_evidence',
       'primary_pathology_primary_lymph_node_presentation_assessment',
       'primary_pathology_lymph_node_examined_count',
       'primary_pathology_number_of_lymphnodes_positive_by_he',
       'primary_pathology_number_of_lymphnodes_positive_by_ihc',
       'primary_pathology_planned_surgery_status',
       'primary_pathology_treatment_prior_to_surgery',
       'primary_pathology_residual_tumor',
       'primary_pathology_karnofsky_performance_score',
       'primary_pathology_eastern_cancer_oncology_group',
       'primary_pathology_radiation_therapy',
       'primary_pathology_postoperative_rx_tx'],
      dtype='object')

In [4]:
cols_to_drop = [
    "Unnamed: 0",
    "patient_barcode",
    "tissue_source_site",
    "patient_id",
    "bcr_patient_uuid",
    "informed_consent_verified",
    "icd_o_3_site",
    "icd_o_3_histology",
    "icd_10",
    "tissue_prospective_collection_indicator",
    "primary_pathology_planned_surgery_status",
    "primary_pathology_treatment_prior_to_surgery",
    "primary_pathology_karnofsky_performance_score",
    "primary_pathology_eastern_cancer_oncology_group"
]
df = df.drop(columns=cols_to_drop, errors='ignore')

In [5]:
print(df.head(5))

  tissue_retrospective_collection_indicator  days_to_birth country_of_birth  \
0                                       YES         -24487              NaN
1                                       YES         -24328              NaN
2                                       YES         -16197              NaN
3                                       YES         -25097              NaN
4                                       YES         -21180              NaN

  gender  height  weight country_of_procurement state_province_of_procurement  \
0   MALE   183.0    95.0            Netherlands                            ZH
1   MALE   178.0    74.0            Netherlands                            ZH
2   MALE   183.0    91.0            Netherlands                            ZH
3   MALE   188.0   100.0            Netherlands                            ZH
4   MALE   189.0    70.0            Netherlands                            ZH

  city_of_procurement race_list  ...  \
0           Rotterdam       NaN  ...
1           Rotterdam       NaN  ...
2           Rotterdam       NaN  ...
3           Rotterdam       NaN  ...
4           Rotterdam       NaN  ...

  primary_pathology_initial_pathologic_diagnosis_method  \
0                             Other method, specify:
1                             Other method, specify:
2                             Other method, specify:
3                             Other method, specify:
4                             Other method, specify:

  primary_pathology_init_pathology_dx_method_other  \
0                               surgical resection
1                               surgical resection
2                               surgical resection
3                               surgical resection
4                               surgical resection

  primary_pathology_lymph_node_metastasis_radiographic_evidence  \
0                                                YES
1                                                 NO
2                                                 NO
3                                                 NO
4                                                 NO

  primary_pathology_primary_lymph_node_presentation_assessment  \
0                                                YES
1                                                YES
2                                                YES
3                                                YES
4                                                YES

  primary_pathology_lymph_node_examined_count  \
0                                         8.0
1                                        19.0
2                                        30.0
3                                         8.0
4                                        19.0

   primary_pathology_number_of_lymphnodes_positive_by_he  \
0                                                7.0
1                                                4.0
2                                                1.0
3                                                4.0
4                                                0.0

   primary_pathology_number_of_lymphnodes_positive_by_ihc  \
0                                                0.0
1                                                0.0
2                                                0.0
3                                                0.0
4                                                0.0

   primary_pathology_residual_tumor  primary_pathology_radiation_therapy  \
0                                R1                                   NO
1                                R1                                   NO
2                                R0                                   NO
3                                R0                                   NO
4                                R0                                   NO

   primary_pathology_postoperative_rx_tx
0                                     NO
1                                     NO
2                                     NO
3                                     NO
4                                     NO

[5 rows x 71 columns]

In [6]:
# ----- 1️⃣ Drop identifier-like columns -----
id_keywords = ["id", "uuid", "barcode", "consent", "site", "Unnamed"]
id_cols = [c for c in df.columns if any(k.lower() in c.lower() for k in id_keywords)]
df = df.drop(columns=id_cols, errors="ignore")

# ----- 2️⃣ Drop columns with very high missing values -----
missing_threshold = 0.6   # drop if >60% NaN
missing_ratio = df.isna().mean()
df = df.drop(columns=missing_ratio[missing_ratio > missing_threshold].index)

# ----- 3️⃣ Drop constant or near-constant columns -----
constant_cols = df.columns[df.nunique() <= 1]
df = df.drop(columns=constant_cols)

# ----- 4️⃣ Optional: show summary of what was dropped -----
print("Dropped ID-like columns:", id_cols)
print("Dropped columns with >60% missing values:", list(missing_ratio[missing_ratio > missing_threshold].index))
print("Dropped constant columns:", list(constant_cols))
print("\nRemaining columns:", df.shape[1])

# View cleaned dataset
print("\nCleaned dataframe preview:")
print(df.head())

Dropped ID-like columns: ['primary_pathology_tumor_tissue_site', 'primary_pathology_esophageal_tumor_involvement_sites', 'primary_pathology_lymph_node_metastasis_radiographic_evidence', 'primary_pathology_residual_tumor']
Dropped columns with >60% missing values: ['days_to_death', 'antireflux_treatment_types', 'h_pylori_infection', 'goblet_cells_present', 'number_of_relatives_diagnosed', 'stage_event_clinical_stage', 'stage_event_psa', 'stage_event_gleason_grading', 'stage_event_ann_arbor', 'stage_event_serum_markers', 'stage_event_igcccg_stage', 'stage_event_masaoka_stage', 'primary_pathology_init_pathology_dx_method_other', 'primary_pathology_number_of_lymphnodes_positive_by_ihc']
Dropped constant columns: ['history_of_neoadjuvant_treatment', 'project', 'primary_pathology_days_to_initial_pathologic_diagnosis']

Remaining columns: 50

Cleaned dataframe preview:
  tissue_retrospective_collection_indicator  days_to_birth country_of_birth  \
0                                       YES         -24487              NaN
1                                       YES         -24328              NaN
2                                       YES         -16197              NaN
3                                       YES         -25097              NaN
4                                       YES         -21180              NaN

  gender  height  weight country_of_procurement state_province_of_procurement  \
0   MALE   183.0    95.0            Netherlands                            ZH
1   MALE   178.0    74.0            Netherlands                            ZH
2   MALE   183.0    91.0            Netherlands                            ZH
3   MALE   188.0   100.0            Netherlands                            ZH
4   MALE   189.0    70.0            Netherlands                            ZH

  city_of_procurement race_list  ...  \
0           Rotterdam       NaN  ...
1           Rotterdam       NaN  ...
2           Rotterdam       NaN  ...
3           Rotterdam       NaN  ...
4           Rotterdam       NaN  ...

  primary_pathology_columnar_mucosa_dysplasia  \
0                       Negative/no dysplasia
1                         Low grade dysplasia
2                                         NaN
3                                         NaN
4                        High grade dysplasia

  primary_pathology_neoplasm_histologic_grade  \
0                                          G3
1                                          G2
2                                          G2
3                                          G2
4                                          G2

  primary_pathology_age_at_initial_pathologic_diagnosis  \
0                                                 67
1                                                 66
2                                                 44
3                                                 68
4                                                 57

  primary_pathology_year_of_initial_pathologic_diagnosis  \
0                                             2001.0
1                                             1999.0
2                                             1998.0
3                                             1999.0
4                                             2000.0

   primary_pathology_initial_pathologic_diagnosis_method  \
0                             Other method, specify:
1                             Other method, specify:
2                             Other method, specify:
3                             Other method, specify:
4                             Other method, specify:

   primary_pathology_primary_lymph_node_presentation_assessment  \
0                                                YES
1                                                YES
2                                                YES
3                                                YES
4                                                YES

   primary_pathology_lymph_node_examined_count  \
0                                          8.0
1                                         19.0
2                                         30.0
3                                          8.0
4                                         19.0

   primary_pathology_number_of_lymphnodes_positive_by_he  \
0                                                7.0
1                                                4.0
2                                                1.0
3                                                4.0
4                                                0.0

   primary_pathology_radiation_therapy primary_pathology_postoperative_rx_tx
0                                   NO                                    NO
1                                   NO                                    NO
2                                   NO                                    NO
3                                   NO                                    NO
4                                   NO                                    NO

[5 rows x 50 columns]

In [17]:
df.to_csv("cleaned.csv")

In [8]:
df.columns

Index(['tissue_retrospective_collection_indicator', 'days_to_birth',
       'country_of_birth', 'gender', 'height', 'weight',
       'country_of_procurement', 'state_province_of_procurement',
       'city_of_procurement', 'race_list', 'ethnicity', 'other_dx',
       'person_neoplasm_cancer_status', 'vital_status',
       'days_to_last_followup', 'tobacco_smoking_history',
       'age_began_smoking_in_years', 'stopped_smoking_year',
       'number_pack_years_smoked', 'alcohol_history_documented',
       'frequency_of_alcohol_consumption',
       'amount_of_alcohol_consumption_per_day', 'reflux_history',
       'initial_diagnosis_by', 'barretts_esophagus',
       'history_of_esophageal_cancer', 'has_new_tumor_events_information',
       'day_of_form_completion', 'month_of_form_completion',
       'year_of_form_completion', 'has_follow_ups_information',
       'has_drugs_information', 'has_radiations_information',
       'stage_event_system_version', 'stage_event_pathologic_stage',
       'stage_event_tnm_categories',
       'primary_pathology_esophageal_tumor_cental_location',
       'primary_pathology_histological_type',
       'primary_pathology_columnar_metaplasia_present',
       'primary_pathology_columnar_mucosa_goblet_cell_present',
       'primary_pathology_columnar_mucosa_dysplasia',
       'primary_pathology_neoplasm_histologic_grade',
       'primary_pathology_age_at_initial_pathologic_diagnosis',
       'primary_pathology_year_of_initial_pathologic_diagnosis',
       'primary_pathology_initial_pathologic_diagnosis_method',
       'primary_pathology_primary_lymph_node_presentation_assessment',
       'primary_pathology_lymph_node_examined_count',
       'primary_pathology_number_of_lymphnodes_positive_by_he',
       'primary_pathology_radiation_therapy',
       'primary_pathology_postoperative_rx_tx'],
      dtype='object')

In [9]:
df

,tissue_retrospective_collection_indicator,days_to_birth,country_of_birth,gender,height,weight,country_of_procurement,state_province_of_procurement,city_of_procurement,race_list,...,primary_pathology_columnar_mucosa_dysplasia,primary_pathology_neoplasm_histologic_grade,primary_pathology_age_at_initial_pathologic_diagnosis,primary_pathology_year_of_initial_pathologic_diagnosis,primary_pathology_initial_pathologic_diagnosis_method,primary_pathology_primary_lymph_node_presentation_assessment,primary_pathology_lymph_node_examined_count,primary_pathology_number_of_lymphnodes_positive_by_he,primary_pathology_radiation_therapy,primary_pathology_postoperative_rx_tx
0,YES,-24487,NaN,MALE,183.0,95.0,Netherlands,ZH,Rotterdam,NaN,...,Negative/no dysplasia,G3,67,2001.0,"Other method, specify:",YES,8.0,7.0,NO,NO
1,YES,-24328,NaN,MALE,178.0,74.0,Netherlands,ZH,Rotterdam,NaN,...,Low grade dysplasia,G2,66,1999.0,"Other method, specify:",YES,19.0,4.0,NO,NO
2,YES,-16197,NaN,MALE,183.0,91.0,Netherlands,ZH,Rotterdam,NaN,...,NaN,G2,44,1998.0,"Other method, specify:",YES,30.0,1.0,NO,NO
3,YES,-25097,NaN,MALE,188.0,100.0,Netherlands,ZH,Rotterdam,NaN,...,NaN,G2,68,1999.0,"Other method, specify:",YES,8.0,4.0,NO,NO
4,YES,-21180,NaN,MALE,189.0,70.0,Netherlands,ZH,Rotterdam,NaN,...,High grade dysplasia,G2,57,2000.0,"Other method, specify:",YES,19.0,0.0,NO,NO
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3980,NO,-19505,Russia,MALE,169.0,67.0,Russia,NaN,Saint petersburg,WHITE,...,NaN,G2,53,2013.0,"Other method, specify:",YES,19.0,0.0,NaN,NaN
3981,NO,-20861,Russia,MALE,165.0,65.0,Russia,NaN,Saint petersburg,WHITE,...,NaN,G3,57,2013.0,"Other method, specify:",YES,9.0,1.0,NaN,NaN
3982,NO,-19438,Russia,MALE,162.0,57.0,Russia,NaN,Saint Petersburg,WHITE,...,NaN,G2,53,2013.0,NaN,NaN,NaN,NaN,NO,NO
3983,NO,-20850,Russia,MALE,161.0,69.0,Russia,NaN,Saint Petersburg,WHITE,...,NaN,G1,57,2013.0,NaN,YES,11.0,0.0,NO,NO
3984,YES,-23820,United Kingdom,MALE,NaN,NaN,United Kingdom,Scotland,Dundee,WHITE,...,High grade dysplasia,G3,65,2012.0,Endoscopic Biopsy,YES,24.0,12.0,NO,NO

In [10]:
import pandas as pd

# Assuming df is already loaded
pd.set_option('display.max_colwidth', None)

for col in df.columns:
    unique_vals = df[col].unique()
    num_unique = len(unique_vals)
    
    print(f"\n========================")
    print(f"Column: {col}")
    print(f"Unique Count: {num_unique}")
    
    # If too many unique values, print only the first 20
    if num_unique > 20:
        print("Unique Values (first 20):", unique_vals[:20])
    else:
        print("Unique Values:", unique_vals)

========================
Column: tissue_retrospective_collection_indicator
Unique Count: 3
Unique Values: ['YES' 'NO' nan]

========================
Column: days_to_birth
Unique Count: 3344
Unique Values (first 20): [-24487 -24328 -16197 -25097 -21180 -16067 -27115 -19484 -25664 -21486
 -29497 -29451 -21640 -25417 -18786 -19755 -26330 -19567 -22316 -22774]

========================
Column: country_of_birth
Unique Count: 9
Unique Values: [nan 'Russia' 'Ukraine' 'Vietnam' 'Bulgaria' 'United States' 'Australia'
 'Brazil' 'United Kingdom']

========================
Column: gender
Unique Count: 2
Unique Values: ['MALE' 'FEMALE']

========================
Column: height
Unique Count: 58
Unique Values (first 20): [183. 178. 188. 189. 180. 173. 179. 185. 170. 168. 165. 176. 169. 182.
 172. 174. 162. 166. 177. 152.]

========================
Column: weight
Unique Count: 109
Unique Values (first 20): [ 95.  74.  91. 100.  70.  80.  85.  77.  82.  83.  67. 102.  48.  73.
  76.  66.  86.  78.  61.  63.]

========================
Column: country_of_procurement
Unique Count: 11
Unique Values: ['Netherlands' 'United States' 'Russia' 'Ukraine' 'Vietnam' 'Bulgaria'
 'Canada' 'Australia' 'Brazil' nan 'United Kingdom']

========================
Column: state_province_of_procurement
Unique Count: 21
Unique Values (first 20): ['ZH' 'Pennsylvania' nan 'Hanoi' 'Ontario' 'New York' 'MI' 'Mi' 'Michigan'
 'michigan' 'Delaware' 'Georgia' 'Texas' 'TX' 'texas' 'Victoria' 'Indiana'
 'NC' 'Sao Paulo' 'az']

========================
Column: city_of_procurement
Unique Count: 29
Unique Values (first 20): ['Rotterdam' 'Piitsburgh' 'Pittsburgh' 'Tver' 'Lviv' 'Kiev' 'Hanoi' 'LVIV'
 nan 'Toronto' 'New York' 'Ann Arbor' 'ANn Arbor' 'Ann arbor' 'ann arbor'
 'ann Arbor' 'Newark' 'London' 'Atlanta' 'Houston']

========================
Column: race_list
Unique Count: 4
Unique Values: [nan 'WHITE' 'ASIAN' 'BLACK OR AFRICAN AMERICAN']

========================
Column: ethnicity
Unique Count: 3
Unique Values: [nan 'NOT HISPANIC OR LATINO' 'HISPANIC OR LATINO']

========================
Column: other_dx
Unique Count: 2
Unique Values: ['No' 'Yes']

========================
Column: person_neoplasm_cancer_status
Unique Count: 3
Unique Values: ['WITH TUMOR' 'TUMOR FREE' nan]

========================
Column: vital_status
Unique Count: 2
Unique Values: ['Dead' 'Alive']

========================
Column: days_to_last_followup
Unique Count: 85
Unique Values (first 20): [       nan  2.340e+02  1.890e+02  0.000e+00  1.000e+00  8.000e+00
  3.000e+01  1.600e+01  1.100e+01  4.000e+00  3.400e+01  1.400e+01
  1.300e+01 -4.000e+00  3.714e+03  1.837e+03  1.638e+03  1.098e+03
  7.730e+02  4.710e+02]

========================
Column: tobacco_smoking_history
Unique Count: 5
Unique Values: [nan  2.  3.  1.  4.]

========================
Column: age_began_smoking_in_years
Unique Count: 28
Unique Values (first 20): [nan 25. 24. 32. 31. 27. 16. 23. 21. 19. 20. 29. 15. 35. 38. 14. 57. 18.
 26. 22.]

========================
Column: stopped_smoking_year
Unique Count: 40
Unique Values (first 20): [  nan 1992. 2012. 1981. 2000. 2013. 2006. 2009. 2008. 2011. 1973. 2010.
 1958. 1949. 1986. 1970. 1977. 1967. 1980. 2005.]

========================
Column: number_pack_years_smoked
Unique Count: 47
Unique Values (first 20): [  nan  40.   22.   30.   50.   37.5  20.   60.   31.   75.   34.   15.
  10.   35.   29.    6.   33.   78.  102.   45. ]

========================
Column: alcohol_history_documented
Unique Count: 3
Unique Values: ['NO' 'YES' nan]

========================
Column: frequency_of_alcohol_consumption
Unique Count: 8
Unique Values: [nan  1.  2.  5.  7.  3.  4.  0.]

========================
Column: amount_of_alcohol_consumption_per_day
Unique Count: 12
Unique Values: [nan  1.  5. 14.  0.  4.  6.  2.  3.  7.  8. 10.]

========================
Column: reflux_history
Unique Count: 3
Unique Values: [nan 'NO' 'YES']

========================
Column: initial_diagnosis_by
Unique Count: 4
Unique Values: ['Symptomatic' nan 'Screening' 'Surveillance']

========================
Column: barretts_esophagus
Unique Count: 4
Unique Values: ['No' 'Yes-UK' 'Yes-USA' nan]

========================
Column: history_of_esophageal_cancer
Unique Count: 3
Unique Values: [nan 'NO' 'YES']

========================
Column: has_new_tumor_events_information
Unique Count: 2
Unique Values: ['YES' 'NO']

========================
Column: day_of_form_completion
Unique Count: 22
Unique Values (first 20): [25  3  1 26 14 11 28 23 21 13 18 16 20 17 12 10 29 22  7 30]

========================
Column: month_of_form_completion
Unique Count: 12
Unique Values: [ 2  4  7  6  8  9  3  5 11 10 12  1]

========================
Column: year_of_form_completion
Unique Count: 4
Unique Values: [2014 2012 2013 2015]

========================
Column: has_follow_ups_information
Unique Count: 2
Unique Values: ['NO' 'YES']

========================
Column: has_drugs_information
Unique Count: 2
Unique Values: ['NO' 'YES']

========================
Column: has_radiations_information
Unique Count: 2
Unique Values: ['NO' 'YES']

========================
Column: stage_event_system_version
Unique Count: 3
Unique Values: ['5th' '7th' '6th']

========================
Column: stage_event_pathologic_stage
Unique Count: 13
Unique Values: ['Stage III' 'Stage IIB' 'Stage I' 'Stage IVA' 'Stage IIA' 'Stage IA'
 'Stage IIIA' 'Stage IIIB' 'Stage IB' 'Stage IIIC' nan 'Stage IV'
 'Stage II']

========================
Column: stage_event_tnm_categories
Unique Count: 54
Unique Values (first 20): ['T3N1M0' 'T1N1M0' 'T1N0M0' 'T3N1M1a' 'T3N0M0' 'T1N1M0T1N0M0' 'T2N0M0'
 'T4N0M0' 'T2N1M0' 'T3N2M0' 'T3N1M0T3N1M0' 'T2NXM1T1N1M0' 'T4aNXMX'
 'T3NXM0' 'T2N3M0' 'T1N0M0T1N0M0' 'T3N1MX' 'T3N0MX' 'T3N2MX' 'T3N2']

========================
Column: primary_pathology_esophageal_tumor_cental_location
Unique Count: 4
Unique Values: ['Distal' 'Mid' 'Proximal' nan]

========================
Column: primary_pathology_histological_type
Unique Count: 2
Unique Values: ['Esophagus Adenocarcinoma, NOS' 'Esophagus Squamous Cell Carcinoma']

========================
Column: primary_pathology_columnar_metaplasia_present
Unique Count: 3
Unique Values: ['NO' 'YES' nan]

========================
Column: primary_pathology_columnar_mucosa_goblet_cell_present
Unique Count: 3
Unique Values: ['NO' nan 'YES']

========================
Column: primary_pathology_columnar_mucosa_dysplasia
Unique Count: 4
Unique Values: ['Negative/no dysplasia' 'Low grade dysplasia' nan 'High grade dysplasia']

========================
Column: primary_pathology_neoplasm_histologic_grade
Unique Count: 4
Unique Values: ['G3' 'G2' 'GX' 'G1']

========================
Column: primary_pathology_age_at_initial_pathologic_diagnosis
Unique Count: 46
Unique Values (first 20): [67 66 44 68 57 43 74 53 70 58 80 59 69 51 54 72 61 62 48 71]

========================
Column: primary_pathology_year_of_initial_pathologic_diagnosis
Unique Count: 16
Unique Values: [2001. 1999. 1998. 2000. 2013. 2011. 2012. 2003. 2006. 2007. 2008. 2009.
 2010. 2005. 2004.   nan]

========================
Column: primary_pathology_initial_pathologic_diagnosis_method
Unique Count: 4
Unique Values: ['Other method, specify:' 'Endoscopic Biopsy' 'Surgical Resection' nan]

========================
Column: primary_pathology_primary_lymph_node_presentation_assessment
Unique Count: 3
Unique Values: ['YES' nan 'NO']

========================
Column: primary_pathology_lymph_node_examined_count
Unique Count: 40
Unique Values (first 20): [ 8. 19. 30.  5.  7. 13. 22. 14.  3. 38.  2. 12.  4. 15.  6. 17.  1. 10.
 nan 20.]

========================
Column: primary_pathology_number_of_lymphnodes_positive_by_he
Unique Count: 15
Unique Values: [ 7.  4.  1.  0.  3.  2.  5.  9.  6. nan  8. 14. 12. 21. 15.]

========================
Column: primary_pathology_radiation_therapy
Unique Count: 3
Unique Values: ['NO' nan 'YES']

========================
Column: primary_pathology_postoperative_rx_tx
Unique Count: 3
Unique Values: ['NO' 'YES' nan]

🔍 What this code achieves
✅ Drops all non-useful, noisy, irrelevant, or leakage columns
✅ Converts birth days → age
✅ Fills missing clinical & lifestyle data
✅ Converts categorical features properly
✅ Prepares data safely for ML (XGBoost, RandomForest, PyTorch Tabular, etc.)

In [11]:
import pandas as pd
import numpy as np

# ------------------------------
# 1. DROP IRRELEVANT / LEAKING / META COLUMNS
# ------------------------------

cols_to_drop = [
    "tissue_retrospective_collection_indicator",
    "country_of_birth",
    "country_of_procurement",
    "state_province_of_procurement",
    "city_of_procurement",
    "day_of_form_completion",
    "month_of_form_completion",
    "year_of_form_completion",
    "has_follow_ups_information",
    "has_drugs_information",
    "has_radiations_information",
    "has_new_tumor_events_information",   # leakage
    "stage_event_tnm_categories",
    "initial_diagnosis_by",               # weak admin info
    "primary_pathology_year_of_initial_pathologic_diagnosis",
    "days_to_birth"                       # will replace with age
]

df = df.drop(columns=[col for col in cols_to_drop if col in df.columns], errors="ignore")

# ------------------------------
# 2. CREATE AGE FEATURE FROM days_to_birth
# ------------------------------

if "days_to_birth" in df.columns:
    df["age"] = -df["days_to_birth"] / 365
else:
    # user already removed; create age only if missing
    pass

# ------------------------------
# 3. CLEAN SMOKING FEATURES
# ------------------------------

# Fill simple missing numeric values with median
for col in [
    "age_began_smoking_in_years",
    "number_pack_years_smoked",
    "frequency_of_alcohol_consumption",
    "amount_of_alcohol_consumption_per_day",
    "stopped_smoking_year"
]:
    if col in df.columns:
        df[col] = df[col].fillna(df[col].median())

# Categorical smoking history
if "tobacco_smoking_history" in df.columns:
    df["tobacco_smoking_history"] = df["tobacco_smoking_history"].astype("category")

# ------------------------------
# 4. CLEAN ALCOHOL / LIFESTYLE
# ------------------------------

for col in ["alcohol_history_documented", "reflux_history", "barretts_esophagus"]:
    if col in df.columns:
        df[col] = df[col].fillna("UNKNOWN").astype("category")

# ------------------------------
# 5. DEMOGRAPHIC CLEANING
# ------------------------------

if "gender" in df.columns:
    df["gender"] = df["gender"].astype("category")

if "race_list" in df.columns:
    df["race_list"] = df["race_list"].fillna("UNKNOWN").astype("category")

if "ethnicity" in df.columns:
    df["ethnicity"] = df["ethnicity"].fillna("UNKNOWN").astype("category")

# ------------------------------
# 6. PATHOLOGY & CLINICAL CLEANING
# ------------------------------

pathology_cats = [
    "stage_event_system_version",
    "stage_event_pathologic_stage",
    "primary_pathology_esophageal_tumor_cental_location",
    "primary_pathology_histological_type",
    "primary_pathology_columnar_metaplasia_present",
    "primary_pathology_columnar_mucosa_goblet_cell_present",
    "primary_pathology_columnar_mucosa_dysplasia",
    "primary_pathology_neoplasm_histologic_grade",
    "primary_pathology_initial_pathologic_diagnosis_method",
    "primary_pathology_primary_lymph_node_presentation_assessment",
    "primary_pathology_radiation_therapy",
    "primary_pathology_postoperative_rx_tx",
]

for col in pathology_cats:
    if col in df.columns:
        df[col] = df[col].fillna("UNKNOWN").astype("category")

# Fill numeric pathology values
num_cols = [
    "primary_pathology_age_at_initial_pathologic_diagnosis",
    "primary_pathology_lymph_node_examined_count",
    "primary_pathology_number_of_lymphnodes_positive_by_he",
]

for col in num_cols:
    if col in df.columns:
        df[col] = df[col].fillna(df[col].median())

# ------------------------------
# 7. VITAL STATUS & FOLLOW-UP
# ------------------------------

if "vital_status" in df.columns:
    df["vital_status"] = df["vital_status"].astype("category")

if "days_to_last_followup" in df.columns:
    df["days_to_last_followup"] = df["days_to_last_followup"].fillna(df["days_to_last_followup"].median())

# ------------------------------
# 8. TARGET CLEANING
# ------------------------------

if "person_neoplasm_cancer_status" in df.columns:
    df = df[df["person_neoplasm_cancer_status"].notna()]       # drop NaNs
    df["person_neoplasm_cancer_status"] = df["person_neoplasm_cancer_status"].astype("category")

# ------------------------------
# 9. FINAL CHECK
# ------------------------------

print("Final columns after cleaning:", df.columns)
print("\nNumber of samples:", len(df))
print("\nData types summary:\n", df.dtypes)

Final columns after cleaning: Index(['gender', 'height', 'weight', 'race_list', 'ethnicity', 'other_dx',
       'person_neoplasm_cancer_status', 'vital_status',
       'days_to_last_followup', 'tobacco_smoking_history',
       'age_began_smoking_in_years', 'stopped_smoking_year',
       'number_pack_years_smoked', 'alcohol_history_documented',
       'frequency_of_alcohol_consumption',
       'amount_of_alcohol_consumption_per_day', 'reflux_history',
       'barretts_esophagus', 'history_of_esophageal_cancer',
       'stage_event_system_version', 'stage_event_pathologic_stage',
       'primary_pathology_esophageal_tumor_cental_location',
       'primary_pathology_histological_type',
       'primary_pathology_columnar_metaplasia_present',
       'primary_pathology_columnar_mucosa_goblet_cell_present',
       'primary_pathology_columnar_mucosa_dysplasia',
       'primary_pathology_neoplasm_histologic_grade',
       'primary_pathology_age_at_initial_pathologic_diagnosis',
       'primary_pathology_initial_pathologic_diagnosis_method',
       'primary_pathology_primary_lymph_node_presentation_assessment',
       'primary_pathology_lymph_node_examined_count',
       'primary_pathology_number_of_lymphnodes_positive_by_he',
       'primary_pathology_radiation_therapy',
       'primary_pathology_postoperative_rx_tx'],
      dtype='object')

Number of samples: 3650

Data types summary:
 gender                                                          category
height                                                           float64
weight                                                           float64
race_list                                                       category
ethnicity                                                       category
other_dx                                                          object
person_neoplasm_cancer_status                                   category
vital_status                                                    category
days_to_last_followup                                            float64
tobacco_smoking_history                                         category
age_began_smoking_in_years                                       float64
stopped_smoking_year                                             float64
number_pack_years_smoked                                         float64
alcohol_history_documented                                      category
frequency_of_alcohol_consumption                                 float64
amount_of_alcohol_consumption_per_day                            float64
reflux_history                                                  category
barretts_esophagus                                              category
history_of_esophageal_cancer                                      object
stage_event_system_version                                      category
stage_event_pathologic_stage                                    category
primary_pathology_esophageal_tumor_cental_location              category
primary_pathology_histological_type                             category
primary_pathology_columnar_metaplasia_present                   category
primary_pathology_columnar_mucosa_goblet_cell_present           category
primary_pathology_columnar_mucosa_dysplasia                     category
primary_pathology_neoplasm_histologic_grade                     category
primary_pathology_age_at_initial_pathologic_diagnosis              int64
primary_pathology_initial_pathologic_diagnosis_method           category
primary_pathology_primary_lymph_node_presentation_assessment    category
primary_pathology_lymph_node_examined_count                      float64
primary_pathology_number_of_lymphnodes_positive_by_he            float64
primary_pathology_radiation_therapy                             category
primary_pathology_postoperative_rx_tx                           category
dtype: object

✅ Drop (useless / irrelevant / non-predictive / leakage risk)
⚠️ Require cleaning
🟩 Keep (predictive for cancer status)

Your target is: person_neoplasm_cancer_status → WITH TUMOR vs TUMOR FREE.

Let's categorize each column systematically.

🚨 FIRST: VARIABLES YOU SHOULD DROP

These provide no clinical predictive value OR introduce noise, irrelevance, or geolocation bias that harms generalization.

❌ 1. Collection / Procurement Metadata

These do NOT relate to cancer biology and will introduce geographical bias.

Column	Reason to Drop
tissue_retrospective_collection_indicator	sampling method metadata
country_of_birth	irrelevant to cancer biology
country_of_procurement	irrelevant
city_of_procurement	irrelevant
state_province_of_procurement	irrelevant
day_of_form_completion	meaningless noise
month_of_form_completion	same
year_of_form_completion	administrative
has_follow_ups_information	metadata flag
has_drugs_information	metadata flag
has_radiations_information	metadata flag
has_new_tumor_events_information	LEAKAGE RISK (drop!)

⚠️ Why drop?
Keeping these will make your model learn where the patient was treated, not their biology — causing overfitting.

❌ 2. Identity / Administrative / Redundant Variables

These add noise or leak future information.

Column	Reason
day_of_form_completion	noise
month_of_form_completion	noise
year_of_form_completion	noise
primary_pathology_year_of_initial_pathologic_diagnosis	confounded by time
initial_diagnosis_by	admin info
❌ 3. High-Cardinality Free-Text or Combined Strings

These contain T, N, M combined codes which SHOULD be decomposed, not used raw.

Column	Reason
stage_event_tnm_categories	Too many formats (54 unique), must parse or drop raw

⚠️ You either:

write a parser to extract T, N, M values
OR

drop the raw column and rely on pathologic stage instead

For simplicity → drop as-is.

⚠️ SECOND: COLUMNS THAT REQUIRE CLEANING (not drop)

These are clinically meaningful but need processing.

🛠️ 1. days_to_birth

Negative values = TCGA format (age in days).

Convert to age:

df['age'] = -df['days_to_birth'] / 365


Then drop days_to_birth.

🛠️ 2. state/city fields (inconsistent capitalization)

IF you decide to keep them (I recommend drop), you must:

lowercase

strip spacing

unify duplicates like "Michigan", "MI", "michigan"

But best choice: drop them entirely.

🛠️ 3. Smoking / Alcohol fields

Keep these, but impute missing values and convert types:

tobacco_smoking_history → categorical

age_began_smoking_in_years → numerical

stopped_smoking_year → use with caution

number_pack_years_smoked → numerical (very predictive)

🟩 THIRD: COLUMNS TO KEEP (strong predictors of cancer status)

These are directly related to tumor biology, diagnosis, stage, or pathology.

✅ Demographics

gender

race_list

ethnicity

weight

height (optional but okay)

✅ Lifestyle risk factors

tobacco_smoking_history

age_began_smoking_in_years

number_pack_years_smoked

alcohol_history_documented

frequency_of_alcohol_consumption

amount_of_alcohol_consumption_per_day

reflux_history

barretts_esophagus (VERY relevant for esophageal cancer)

✅ Clinical / Follow-Up / Vital

vital_status

days_to_last_followup (use carefully — it can be near-leakage if follow-up came after tumor removal)

Use this but understand it introduces time bias.

✅ Staging and Pathology

These are the MOST predictive:

stage_event_system_version

stage_event_pathologic_stage (STRONG predictor)

primary_pathology_esophageal_tumor_cental_location

primary_pathology_histological_type

primary_pathology_columnar_metaplasia_present

primary_pathology_columnar_mucosa_goblet_cell_present

primary_pathology_columnar_mucosa_dysplasia

primary_pathology_neoplasm_histologic_grade

primary_pathology_age_at_initial_pathologic_diagnosis

primary_pathology_initial_pathologic_diagnosis_method

primary_pathology_primary_lymph_node_presentation_assessment

primary_pathology_lymph_node_examined_count

primary_pathology_number_of_lymphnodes_positive_by_he

primary_pathology_radiation_therapy

primary_pathology_postoperative_rx_tx

✔️ FINAL RECOMMENDATION LIST
❌ Drop these columns entirely
tissue_retrospective_collection_indicator
country_of_birth
country_of_procurement
state_province_of_procurement
city_of_procurement
day_of_form_completion
month_of_form_completion
year_of_form_completion
has_follow_ups_information
has_drugs_information
has_radiations_information
has_new_tumor_events_information
stage_event_tnm_categories
initial_diagnosis_by (optional)
primary_pathology_year_of_initial_pathologic_diagnosis (optional)
days_to_birth (after converting to age)

⚠️ Columns requiring transformation / cleaning
days_to_birth  → convert to age_in_years
stopped_smoking_year → convert to years_since_stopped if needed
state_province_of_procurement → should be dropped or normalized
city_of_procurement → drop
stage_event_pathologic_stage → encode ordinally (Stage I < Stage II < Stage III…)

🟩 Keep these columns

Everything not in the “drop” list AND directly related to biological or clinical prediction

In [12]:
df

,gender,height,weight,race_list,ethnicity,other_dx,person_neoplasm_cancer_status,vital_status,days_to_last_followup,tobacco_smoking_history,...,primary_pathology_columnar_mucosa_goblet_cell_present,primary_pathology_columnar_mucosa_dysplasia,primary_pathology_neoplasm_histologic_grade,primary_pathology_age_at_initial_pathologic_diagnosis,primary_pathology_initial_pathologic_diagnosis_method,primary_pathology_primary_lymph_node_presentation_assessment,primary_pathology_lymph_node_examined_count,primary_pathology_number_of_lymphnodes_positive_by_he,primary_pathology_radiation_therapy,primary_pathology_postoperative_rx_tx
0,MALE,183.0,95.0,UNKNOWN,UNKNOWN,No,WITH TUMOR,Dead,105.0,NaN,...,NO,Negative/no dysplasia,G3,67,"Other method, specify:",YES,8.0,7.0,NO,NO
1,MALE,178.0,74.0,UNKNOWN,UNKNOWN,No,WITH TUMOR,Dead,105.0,NaN,...,NO,Low grade dysplasia,G2,66,"Other method, specify:",YES,19.0,4.0,NO,NO
2,MALE,183.0,91.0,UNKNOWN,UNKNOWN,No,WITH TUMOR,Dead,105.0,NaN,...,UNKNOWN,UNKNOWN,G2,44,"Other method, specify:",YES,30.0,1.0,NO,NO
3,MALE,188.0,100.0,UNKNOWN,UNKNOWN,No,WITH TUMOR,Dead,105.0,NaN,...,UNKNOWN,UNKNOWN,G2,68,"Other method, specify:",YES,8.0,4.0,NO,NO
4,MALE,189.0,70.0,UNKNOWN,UNKNOWN,No,WITH TUMOR,Dead,105.0,NaN,...,UNKNOWN,High grade dysplasia,G2,57,"Other method, specify:",YES,19.0,0.0,NO,NO
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3978,FEMALE,NaN,55.0,WHITE,HISPANIC OR LATINO,No,TUMOR FREE,Alive,1254.0,4.0,...,NO,Negative/no dysplasia,G2,63,Endoscopic Biopsy,YES,9.0,0.0,NO,NO
3979,MALE,NaN,64.0,BLACK OR AFRICAN AMERICAN,HISPANIC OR LATINO,No,TUMOR FREE,Alive,437.0,2.0,...,NO,High grade dysplasia,G1,49,Endoscopic Biopsy,YES,10.0,1.0,YES,YES
3981,MALE,165.0,65.0,WHITE,NOT HISPANIC OR LATINO,No,TUMOR FREE,Alive,0.0,1.0,...,UNKNOWN,UNKNOWN,G3,57,"Other method, specify:",YES,9.0,1.0,UNKNOWN,UNKNOWN
3982,MALE,162.0,57.0,WHITE,NOT HISPANIC OR LATINO,No,TUMOR FREE,Alive,15.0,1.0,...,UNKNOWN,UNKNOWN,G2,53,UNKNOWN,UNKNOWN,12.0,1.0,NO,NO
3983,MALE,161.0,69.0,WHITE,NOT HISPANIC OR LATINO,No,TUMOR FREE,Alive,18.0,4.0,...,UNKNOWN,UNKNOWN,G1,57,UNKNOWN,YES,11.0,0.0,NO,NO

In [14]:
len(df.columns)

34

In [13]:
import pandas as pd

# Assuming df is already loaded
pd.set_option('display.max_colwidth', None)

for col in df.columns:
    unique_vals = df[col].unique()
    num_unique = len(unique_vals)
    
    print(f"\n========================")
    print(f"Column: {col}")
    print(f"Unique Count: {num_unique}")
    
    # If too many unique values, print only the first 20
    if num_unique > 20:
        print("Unique Values (first 20):", unique_vals[:20])
    else:
        print("Unique Values:", unique_vals)

========================
Column: gender
Unique Count: 2
Unique Values: ['MALE', 'FEMALE']
Categories (2, object): ['FEMALE', 'MALE']

========================
Column: height
Unique Count: 58
Unique Values (first 20): [183. 178. 188. 189. 180. 173. 179. 185. 170. 168. 165. 176. 169. 182.
 172. 174. 162. 166. 177. 152.]

========================
Column: weight
Unique Count: 99
Unique Values (first 20): [ 95.  74.  91. 100.  70.  80.  85.  77.  82.  83.  67. 102.  48.  73.
  76.  66.  86.  78.  61.  63.]

========================
Column: race_list
Unique Count: 4
Unique Values: ['UNKNOWN', 'WHITE', 'ASIAN', 'BLACK OR AFRICAN AMERICAN']
Categories (4, object): ['ASIAN', 'BLACK OR AFRICAN AMERICAN', 'UNKNOWN', 'WHITE']

========================
Column: ethnicity
Unique Count: 3
Unique Values: ['UNKNOWN', 'NOT HISPANIC OR LATINO', 'HISPANIC OR LATINO']
Categories (3, object): ['HISPANIC OR LATINO', 'NOT HISPANIC OR LATINO', 'UNKNOWN']

========================
Column: other_dx
Unique Count: 2
Unique Values: ['No' 'Yes']

========================
Column: person_neoplasm_cancer_status
Unique Count: 2
Unique Values: ['WITH TUMOR', 'TUMOR FREE']
Categories (2, object): ['TUMOR FREE', 'WITH TUMOR']

========================
Column: vital_status
Unique Count: 2
Unique Values: ['Dead', 'Alive']
Categories (2, object): ['Alive', 'Dead']

========================
Column: days_to_last_followup
Unique Count: 74
Unique Values (first 20): [ 1.050e+02  2.340e+02  1.890e+02  0.000e+00  1.000e+00  8.000e+00
  3.000e+01  1.600e+01  1.100e+01  4.000e+00  3.400e+01  1.400e+01
  1.300e+01 -4.000e+00  3.714e+03  1.837e+03  1.638e+03  1.098e+03
  7.730e+02  4.710e+02]

========================
Column: tobacco_smoking_history
Unique Count: 5
Unique Values: [NaN, 2.0, 3.0, 1.0, 4.0]
Categories (4, float64): [1.0, 2.0, 3.0, 4.0]

========================
Column: age_began_smoking_in_years
Unique Count: 27
Unique Values (first 20): [20. 25. 24. 32. 31. 27. 16. 23. 21. 19. 15. 35. 38. 14. 57. 18. 26. 22.
 33. 30.]

========================
Column: stopped_smoking_year
Unique Count: 33
Unique Values (first 20): [1989. 1992. 2012. 1981. 2000. 2013. 2006. 2009. 2008. 2011. 1973. 2010.
 1958. 1977. 1967. 1980. 1985. 1976. 1994. 1968.]

========================
Column: number_pack_years_smoked
Unique Count: 43
Unique Values (first 20): [ 31.   40.   22.   30.   50.   37.5  20.   60.   75.   34.   15.   10.
  35.   29.    6.   33.  102.   45.   54.   48. ]

========================
Column: alcohol_history_documented
Unique Count: 3
Unique Values: ['NO', 'YES', 'UNKNOWN']
Categories (3, object): ['NO', 'UNKNOWN', 'YES']

========================
Column: frequency_of_alcohol_consumption
Unique Count: 7
Unique Values: [3. 1. 2. 5. 7. 4. 0.]

========================
Column: amount_of_alcohol_consumption_per_day
Unique Count: 11
Unique Values: [ 1.  5. 14.  0.  4.  6.  2.  3.  7.  8. 10.]

========================
Column: reflux_history
Unique Count: 3
Unique Values: ['UNKNOWN', 'NO', 'YES']
Categories (3, object): ['NO', 'UNKNOWN', 'YES']

========================
Column: barretts_esophagus
Unique Count: 4
Unique Values: ['No', 'Yes-UK', 'Yes-USA', 'UNKNOWN']
Categories (4, object): ['No', 'UNKNOWN', 'Yes-UK', 'Yes-USA']

========================
Column: history_of_esophageal_cancer
Unique Count: 3
Unique Values: [nan 'NO' 'YES']

========================
Column: stage_event_system_version
Unique Count: 3
Unique Values: ['5th', '7th', '6th']
Categories (3, object): ['5th', '6th', '7th']

========================
Column: stage_event_pathologic_stage
Unique Count: 13
Unique Values: ['Stage III', 'Stage IIB', 'Stage I', 'Stage IVA', 'Stage IIA', ..., 'Stage IB', 'Stage IIIC', 'Stage IV', 'UNKNOWN', 'Stage II']
Length: 13
Categories (13, object): ['Stage I', 'Stage IA', 'Stage IB', 'Stage II', ..., 'Stage IIIC', 'Stage IV', 'Stage IVA', 'UNKNOWN']

========================
Column: primary_pathology_esophageal_tumor_cental_location
Unique Count: 4
Unique Values: ['Distal', 'Mid', 'Proximal', 'UNKNOWN']
Categories (4, object): ['Distal', 'Mid', 'Proximal', 'UNKNOWN']

========================
Column: primary_pathology_histological_type
Unique Count: 2
Unique Values: ['Esophagus Adenocarcinoma, NOS', 'Esophagus Squamous Cell Carcinoma']
Categories (2, object): ['Esophagus Adenocarcinoma, NOS', 'Esophagus Squamous Cell Carcinoma']

========================
Column: primary_pathology_columnar_metaplasia_present
Unique Count: 3
Unique Values: ['NO', 'YES', 'UNKNOWN']
Categories (3, object): ['NO', 'UNKNOWN', 'YES']

========================
Column: primary_pathology_columnar_mucosa_goblet_cell_present
Unique Count: 3
Unique Values: ['NO', 'UNKNOWN', 'YES']
Categories (3, object): ['NO', 'UNKNOWN', 'YES']

========================
Column: primary_pathology_columnar_mucosa_dysplasia
Unique Count: 4
Unique Values: ['Negative/no dysplasia', 'Low grade dysplasia', 'UNKNOWN', 'High grade dysplasia']
Categories (4, object): ['High grade dysplasia', 'Low grade dysplasia', 'Negative/no dysplasia', 'UNKNOWN']

========================
Column: primary_pathology_neoplasm_histologic_grade
Unique Count: 4
Unique Values: ['G3', 'G2', 'GX', 'G1']
Categories (4, object): ['G1', 'G2', 'G3', 'GX']

========================
Column: primary_pathology_age_at_initial_pathologic_diagnosis
Unique Count: 46
Unique Values (first 20): [67 66 44 68 57 43 74 53 70 58 80 59 69 51 54 72 61 62 48 71]

========================
Column: primary_pathology_initial_pathologic_diagnosis_method
Unique Count: 4
Unique Values: ['Other method, specify:', 'Endoscopic Biopsy', 'Surgical Resection', 'UNKNOWN']
Categories (4, object): ['Endoscopic Biopsy', 'Other method, specify:', 'Surgical Resection', 'UNKNOWN']

========================
Column: primary_pathology_primary_lymph_node_presentation_assessment
Unique Count: 3
Unique Values: ['YES', 'UNKNOWN', 'NO']
Categories (3, object): ['NO', 'UNKNOWN', 'YES']

========================
Column: primary_pathology_lymph_node_examined_count
Unique Count: 37
Unique Values (first 20): [ 8. 19. 30.  5.  7. 13. 22. 14.  3. 38.  2. 12.  4. 15.  6. 17.  1. 10.
 20. 24.]

========================
Column: primary_pathology_number_of_lymphnodes_positive_by_he
Unique Count: 12
Unique Values: [ 7.  4.  1.  0.  3.  2.  5.  9.  6.  8. 14. 15.]

========================
Column: primary_pathology_radiation_therapy
Unique Count: 3
Unique Values: ['NO', 'UNKNOWN', 'YES']
Categories (3, object): ['NO', 'UNKNOWN', 'YES']

========================
Column: primary_pathology_postoperative_rx_tx
Unique Count: 3
Unique Values: ['NO', 'YES', 'UNKNOWN']
Categories (3, object): ['NO', 'UNKNOWN', 'YES']